### ISSUE TITLE
SDK

### ISSUE THREAD

**Issue by jbec1901** [Tiltify/api#11]
So I made this: https://github.com/jbec1901/TiltifyV3.0API

I have not made it into a easy to install npm app yet but it functions as far as I can tell.

**Comment by Eein** [comment]
This is cool!
When we have a free moment to update our documentation, we'll likely start adding SDK's to a section in the docs.

Thanks for sharing. I'll leave this issue alive as a reminder to create that section when possible.

**Comment by Eein** [comment]
I added this SDK to our api docs, sorry for taking so long!
https://tiltify.github.io/api/topics/sdks.html
