### ISSUE TITLE
Another SDK

### ISSUE THREAD

**Issue by daniellockard** [Tiltify/api#12]
Hey! I wrote this over the last little bit - I'm porting my other tiltify projects to using it soon. Here's a link https://github.com/daniellockard/tiltify-api-client

I know y'all aren't probably going to add a list of SDKs right now, but figured this would be a good reminder that a list of SDKs might help some people.

Also have docs up on https://daniellockard.github.io/tiltify-api-client/.

It's also available on npm as tiltify-api-client

**Comment by Eein** [comment]
Hello!

Thanks for your hard work :) We do plan on making an SDK list, i'll leave this issue up as a reminder to go back and add these.

Thanks again!

**Comment by Eein** [comment]
I went ahead and updated this this morning! 

Thanks for sharing your hard work!

https://tiltify.github.io/api/topics/sdks.html
