### ISSUE TITLE
SDK page error

### ISSUE THREAD

**Issue by jbec1901** [Tiltify/api#14]
jbec1901/TiltifyV3.0API Repo link points to https://github.com/daniellockard/tiltify-api-client but should point to https://github.com/jbec1901/TiltifyV3.0API

**Comment by Eein** [comment]
i'm pushing to to show the repo since thats where the docs are at - if you have a better documentation, let me know

Thanks for your help with making a tool for the community! :)

**Comment by jbec1901** [comment]
I know why you are doing it but for jbec1901/TiltifyV3.0API you are showing the repo for daniellockard/tiltify-api-client when they are separate pages with separate documentation.

The docs column is fine but the repo column is incorrect.

**Comment by Eein** [comment]
Let me know if its good now!

**Comment by jbec1901** [comment]
Its good
