### ISSUE TITLE
Authorising via OAuth2 +/v3/me/is-profile-complete problem

### ISSUE THREAD

**Issue by dunknicoll** [Tiltify/api#16]
Hi there,

When trying to use OAuth2 to authorise users, when a user logs in with email + password, even though it's successful they get sent to a page that asks them to complete their profile (`In order to continue using this website, you must complete your user profile, by filling in the missing information.`) even though it's already completed and unfortunately the button to submit the form is disabled/grayed out.

(Even when making a change which activates the button, submitting it does nothing)

It seems to check `https://tiltify.com/api/v3/me/is-profile-complete` and return a 401 even though the call just before it to `https://tiltify.com/users/session/create?redirect_url=...` returns a 200 and the profile information.

This is used in a service that has previously been working without issue and aids in a friends reasonably sized campaign that is upcoming so any and all help is massively appreciated.

Many thanks

**Comment by Eein** [comment]
Thanks for the report! I'll get this to the team asap.

In the meantime, can you make sure that browser autofill isn't doing anything weird? My first thought is some validations aren't triggering properly.
Some steps you can take are just adding and removing characters in all the boxes to ensure validations are triggering properly.

We'll attempt to replicate and fix in the morning.

Thanks again!

**Comment by dunknicoll** [comment]
Hi Eein,

Thanks for replying! There's definitely no autofill happening (and I don't believe this page should show anyway, it certainly hadn't previously).

Both my friend and I have replicated this with our respective accounts. I should note that the authorisation is being requested from within an Electron app but I've also replicated it using Postman.

If it helps for your replicating of the issue, please see the following video - https://streamable.com/jj0qj2

Thanks :)

**Comment by Eein** [comment]
Cursory research is showing this is only happening to email and pass login - we'll keep you updated as soon as we know :)

**Comment by Eein** [comment]
I'm created a new account and am having trouble replicating - it seems to be working fine with email and pass.
We are chasing down a mac and some older user accounts to do some additional testing. Could you open the inspector in the prompt window and send us the network tab?

Thanks!

**Comment by dunknicoll** [comment]
Hi @Eein , thanks for looking at this so quickly!

Here's the network tab when replicating both in the electron app and in postman respectively (hope that's what you are after but left me know if you wanted something else).

[Electron App Screenshot](https://f000.backblazeb2.com/file/dunktemp/electron-app-tiltify.png)
[Postman Screenshot](https://f000.backblazeb2.com/file/dunktemp/postman-tiltify.png)

I should note that my friend who is able to replicate this issue is not on a mac.

Thanks again for all your help on this, really appreciate it. Please don't hesitate to let me know if there's anything else you need from me.

**Comment by Eein** [comment]
Close! Can you grab the response out of network from the `is-profile-complete` 401? If it contains any PII, feel free to submit in the ticket you opened.

**Comment by Eein** [comment]
Note: Resolution was outdated postman - potentially a chromium issue. Closing for now. :)
