### ISSUE TITLE
Remove V2 links

### ISSUE THREAD

**Issue by deefdragon** [Tiltify/api#25]
Given the V2 has sunset by 3 years, and the fact that the knowledge-base article it links to 404s, it should likely be removed from the docs.

(also, if I have an api request, would I file an issue here? "or you have any problems" technically applies to not having a required endpoint)

**Comment by Eein** [comment]
I'll keep this issue open to update the docs soon

If you have an api request,  send it through https://info.tiltify.com/support/home to make sure the most eyes see it.

Thanks!
