### ISSUE TITLE
Ratelimit information

### ISSUE THREAD

**Issue by dennisrijsdijk** [Tiltify/api#27]
I'm planning on making an application that frequently (several times per minute) checks the donations on a campaign, for several broadcasters at a time. I would like to learn about the ratelimits Tiltify imposes, so that I can ensure I can remain within those limits in my own application.

**Comment by Eein** [comment]
Our rate limit isn't a hard number, but as long as you're not being abusive you should be fine. A very safe number is keeping it under 5 requests per second to keep you off the radar, but less is better if you can.

Thanks!
