### ISSUE TITLE
No query document supplied

### ISSUE THREAD

**Issue by shelchang** [Tiltify/api#30]
Trying to get campaign info using /campaigns/:id, I'm getting the response
`{"errors": [{"message": "No query document supplied"}]}`

Also, the URL given in the API documentation https://tiltify.com/api/v3/campaigns/[id] returns a 404; the URL that works is https://api.tiltify.com/campaigns/[id]

**Comment by mochanekodev** [comment]
I am attempting to get campaign donation info using the supplied URL format
`https://tiltify.com/api/v3/campaigns/[ID]/donations`
But I am getting a 403 error
`{"meta":{"status":403},"error":{"title":"Forbidden","detail":"You are forbidden from accessing this resource."}}`

When using the URL format @shelchang provided, I get the "No query document supplied" error
`{"errors":[{"message":"No query document supplied"}]}`

**Comment by Eein** [comment]
It looks like both of you are hitting our site graphql api - I wouldn't recommend it as the api changes quite often.

Please see the v3 api documentation to get started with your own apps; 

https://tiltify.github.io/api/topics/getting-started.html 

To use our api, you'll need to authenticate by making an application, but you'll see more of that in the above link :)

Thanks!

Feel free to reopen if there is still an issue.
