### ISSUE TITLE
Poll sample has incorrect dataset

### ISSUE THREAD

**Issue by JBelkin** [Tiltify/api#5]
If you look at the example provided here:
https://github.com/Tiltify/api/blob/master/docs/endpoints/campaigns-id-polls.md

There is an egregious misrepresentation of people who actually prefer pineapple on pizza.

![image](https://user-images.githubusercontent.com/11177128/32073211-49964196-ba63-11e7-9e8f-7a876133979d.png)
This should read much closer to 100% as everyone should enjoy pineapple on their pizza.

**Comment by sammydavisjrjr** [comment]
We will definitely look into this egregious misrepresentation.
