### ISSUE TITLE
How open are you to changing some docs?

### ISSUE THREAD

**Issue by daniellockard** [Tiltify/api#8]
Hello,

I started implementing a tiltify client in `Go` and started running into issues.

- https://tiltify.com/api/v3/fundraising-events gives `{"meta":{"status":501},"error":{"title":"Not Implemented","detail":"The resource has not been implemented."}}%`
- Trying to query Cause Campaigns `GET /causes/:id/campaigns` does not work it seems. I checked the example ID and some others and they all said not authorized? It'd be cool if all of the examples had a working ID. 
- Any JSON example with //... doesn't work going through a code generator for JSON. At least one had trailing commas where there shouldn't be (as much as I wish the spec did allow it)
- Some of the JSON doesn't have commas where it's needed. `GET /causes/:id/fundraising-events` on the endsOn.

I haven't gotten any further... I wanted to see if I could PR your docs or if there's a process for that.

**Comment by Eein** [comment]
Hello! 

There is some endpoints that we were planning on implementing and just haven't had time to get around to, there may actually be another couple with the same issue.

If you see anything that doesn't work, like cause campaigns, definitely let us know and we'll spend some time looking at it.

We'd love a PR with mistakes like trailing commas or anything you'd like to help with. 

Thanks again for the feedback! We're excited to see a `go` library!

**Comment by daniellockard** [comment]
Awesome! Currently I'm seeing issues with Cause Fundraising events in that `video` of each `event` is rather null than just an empty object with blank value. I'm unconvinced that the JSON on the page for that is a correct, but I can't tell without an event with a non-null video.

I also have my tests skipped for `GET /causes/:id/donations`, probably because that's private to the cause so there's no IDs that would return anything to me with my key, unless there's a test `cause` available or something?

I skipped `GET /causes/:id/campaigns` as well because also I tried with id 35 "St. Jude" and it told me I was not authorized, can you maybe point me at an ID that would pass the test for that?

**Comment by daniellockard** [comment]
Also my work-in-progress is here: https://github.com/daniellockard/tiltify

**Comment by Eein** [comment]
> I also have my tests skipped for GET /causes/:id/donations, probably because that's private to the cause so there's no IDs that would return anything to me with my key, unless there's a test cause available or something?

Its definitely private at the moment. We originally used this documentation for internal use and just kinda scrapped it together for everyone else. 

> I skipped GET /causes/:id/campaigns as well because also I tried with id 35 "St. Jude" and it told me I was not authorized, can you maybe point me at an ID that would pass the test for that?

I believe this endpoint will not work for a standard user account. I believe we intended on making it available and may do so in the future, but we need to get past the red tape on this one. :)

**Comment by daniellockard** [comment]
Cool. I'll implement it and Skip() my tests for those functions.

**Comment by Eein** [comment]
I'm closing this ticket due to age. If you decide to do a PR, feel free :)
