### ISSUE TITLE
Safe usage to avoid rate limiting

### ISSUE THREAD

**Issue by Corosauce** [Tiltify/api#9]
Hi there, I am working on a project for an upcoming live stream that will make use of the API to integrate into minecraft to notify the players and stream of new donations and their messages etc.

I couldn't find any info on usage rates so I figure I'd ask here, what would be the safe usage amounts? For example I was looking to query donations via https://tiltify.com/api/v3/campaigns/ID/donations?count=20 every 5-15 seconds, the more frequently I can query the better. We don't anticipate a heavy influx of donations so I could lower the count parameter further, etc.

Any info would be much appreciated, thanks!

**Comment by Eein** [comment]
Hello! Every 5 seconds should be perfectly acceptable.

We currently do not have any hard rules, we just ask people to be kind or we'll have to blacklist. 

Good luck with your campaign!

**Comment by Corosauce** [comment]
Ah perfect, and thanks!
